// <auto-generated />
using System;
using MachineCommandCenter.Shared.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MachineCommandCenter.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211101133458_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MachineCommandCenter.Shared.Models.Machine", b =>
                {
                    b.Property<Guid>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MachineStatus")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentDataDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("MachineId");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            MachineId = new Guid("d3ef0437-c6bf-4654-bfea-c6883d7e11d6"),
                            MachineStatus = 1,
                            Name = "Telehandler",
                            SentDataDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2009)
                        },
                        new
                        {
                            MachineId = new Guid("a480ba91-7618-4d95-92e1-751a08560bf3"),
                            MachineStatus = 0,
                            Name = "Single Man Lift",
                            SentDataDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2009)
                        },
                        new
                        {
                            MachineId = new Guid("9f552147-0b76-4666-82a8-79008e09e1ba"),
                            MachineStatus = 1,
                            Name = "Wheel Tractor-Scraper",
                            SentDataDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2009)
                        },
                        new
                        {
                            MachineId = new Guid("6500ff82-31fd-405d-a06b-41bf25070d68"),
                            MachineStatus = 0,
                            Name = "Skid Steer Loader",
                            SentDataDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2009)
                        },
                        new
                        {
                            MachineId = new Guid("2ad53da7-d8ca-4b89-9464-1904e0e461de"),
                            MachineStatus = 0,
                            Name = "Scissor Lift",
                            SentDataDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2009)
                        },
                        new
                        {
                            MachineId = new Guid("08c04174-171e-4c19-a615-4053b688464c"),
                            MachineStatus = 1,
                            Name = "Forklift",
                            SentDataDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1981)
                        },
                        new
                        {
                            MachineId = new Guid("a570092a-6e93-4236-8bc9-631da397abb4"),
                            MachineStatus = 1,
                            Name = "Bulldozer",
                            SentDataDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1980)
                        },
                        new
                        {
                            MachineId = new Guid("8fe7dba0-354a-40f9-9fd4-4f4079a814fc"),
                            MachineStatus = 0,
                            Name = "Backhoe Loader",
                            SentDataDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2009)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
