// <auto-generated />
using System;
using MachineCommandCenter.Shared.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MachineCommandCenter.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211102160213_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MachineCommandCenter.Shared.Models.Machine", b =>
                {
                    b.Property<Guid>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MachineStatus")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentDataDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("MachineId");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            MachineId = new Guid("bb67207e-af12-4a46-a419-e2e9b9805ed6"),
                            MachineStatus = 1,
                            Name = "Telehandler",
                            SentDataDateTime = new DateTime(2021, 11, 2, 17, 2, 12, 944, DateTimeKind.Local).AddTicks(8118)
                        },
                        new
                        {
                            MachineId = new Guid("2535cc65-41e2-4eb7-a505-63ad71c6e73b"),
                            MachineStatus = 0,
                            Name = "Single Man Lift",
                            SentDataDateTime = new DateTime(2021, 11, 2, 17, 2, 12, 949, DateTimeKind.Local).AddTicks(2329)
                        },
                        new
                        {
                            MachineId = new Guid("aad1eb46-64f1-4c7f-9b7d-cbdc18e24b2f"),
                            MachineStatus = 1,
                            Name = "Wheel Tractor-Scraper",
                            SentDataDateTime = new DateTime(2021, 11, 2, 17, 2, 12, 949, DateTimeKind.Local).AddTicks(2554)
                        },
                        new
                        {
                            MachineId = new Guid("f88bd76f-26d5-45ac-88a6-80d2765ce39c"),
                            MachineStatus = 0,
                            Name = "Skid Steer Loader",
                            SentDataDateTime = new DateTime(2021, 11, 2, 17, 2, 12, 949, DateTimeKind.Local).AddTicks(2611)
                        },
                        new
                        {
                            MachineId = new Guid("e6d0152b-d055-4dc8-8980-ccc38a3337b3"),
                            MachineStatus = 0,
                            Name = "Scissor Lift",
                            SentDataDateTime = new DateTime(2021, 11, 2, 17, 2, 12, 949, DateTimeKind.Local).AddTicks(2659)
                        },
                        new
                        {
                            MachineId = new Guid("bd5ba167-44be-46f7-b884-573d12240605"),
                            MachineStatus = 1,
                            Name = "Forklift",
                            SentDataDateTime = new DateTime(2021, 11, 2, 17, 2, 12, 949, DateTimeKind.Local).AddTicks(2720)
                        },
                        new
                        {
                            MachineId = new Guid("34fd4f7e-9f3c-4e8a-848a-2ca4b6b2aaf6"),
                            MachineStatus = 1,
                            Name = "Bulldozer",
                            SentDataDateTime = new DateTime(2021, 11, 2, 17, 2, 12, 949, DateTimeKind.Local).AddTicks(2781)
                        },
                        new
                        {
                            MachineId = new Guid("b8b8fa7d-adfe-4dd7-9846-7a313a1ba4ca"),
                            MachineStatus = 0,
                            Name = "Backhoe Loader",
                            SentDataDateTime = new DateTime(2021, 11, 2, 17, 2, 12, 949, DateTimeKind.Local).AddTicks(2832)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
